INSERT INTO generos (id, name) VALUES (1, 'operatic pop');
INSERT INTO generos (id, name) VALUES (2, 'canadian singer-songwriter');
INSERT INTO generos (id, name) VALUES (3, 'hardcore hip hop');
INSERT INTO generos (id, name) VALUES (4, 'stomp and holler');
INSERT INTO generos (id, name) VALUES (5, 'chicago hardcore');
INSERT INTO generos (id, name) VALUES (6, 'neo mellow');
INSERT INTO generos (id, name) VALUES (7, 'british soul');
INSERT INTO generos (id, name) VALUES (8, 'chicago punk');
INSERT INTO generos (id, name) VALUES (9, 'atl trap');
INSERT INTO generos (id, name) VALUES (10, 'tropical');
INSERT INTO generos (id, name) VALUES (11, 'new wave pop');
INSERT INTO generos (id, name) VALUES (12, 'australian psych');
INSERT INTO generos (id, name) VALUES (13, 'funk pop');
INSERT INTO generos (id, name) VALUES (14, 'emo rap');
INSERT INTO generos (id, name) VALUES (15, 'salsa');
INSERT INTO generos (id, name) VALUES (16, 'neo-singer-songwriter');
INSERT INTO generos (id, name) VALUES (17, 'pop punk');
INSERT INTO generos (id, name) VALUES (18, 'modern alternative pop');
INSERT INTO generos (id, name) VALUES (19, 'athens indie');
INSERT INTO generos (id, name) VALUES (20, 'electropowerpop');
INSERT INTO generos (id, name) VALUES (21, 'pop emo');
INSERT INTO generos (id, name) VALUES (22, 'canadian pop punk');
INSERT INTO generos (id, name) VALUES (23, 'scandipop');
INSERT INTO generos (id, name) VALUES (24, 'trance');
INSERT INTO generos (id, name) VALUES (25, 'complextro');
INSERT INTO generos (id, name) VALUES (26, 'modern rock');
INSERT INTO generos (id, name) VALUES (27, 'portland hip hop');
INSERT INTO generos (id, name) VALUES (28, 'dutch edm');
INSERT INTO generos (id, name) VALUES (29, 'adult standards');
INSERT INTO generos (id, name) VALUES (30, 'rap latina');
INSERT INTO generos (id, name) VALUES (31, 'future house');
INSERT INTO generos (id, name) VALUES (32, 'singer-songwriter');
INSERT INTO generos (id, name) VALUES (33, 'teen pop');
INSERT INTO generos (id, name) VALUES (34, 'pop house');
INSERT INTO generos (id, name) VALUES (35, 'neo soul');
INSERT INTO generos (id, name) VALUES (36, 'rap conscient');
INSERT INTO generos (id, name) VALUES (37, 'hip house');
INSERT INTO generos (id, name) VALUES (38, 'irish rock');
INSERT INTO generos (id, name) VALUES (39, 'rap');
INSERT INTO generos (id, name) VALUES (40, 'icelandic indie');
INSERT INTO generos (id, name) VALUES (41, 'afro r&b');
INSERT INTO generos (id, name) VALUES (42, 'philly rap');
INSERT INTO generos (id, name) VALUES (43, 'israeli rock');
INSERT INTO generos (id, name) VALUES (44, 'modern country rock');
INSERT INTO generos (id, name) VALUES (45, 'garage rock');
INSERT INTO generos (id, name) VALUES (46, 'canadian pop');
INSERT INTO generos (id, name) VALUES (47, 'melancholia');
INSERT INTO generos (id, name) VALUES (48, 'new rave');
INSERT INTO generos (id, name) VALUES (49, 'christian rock');
INSERT INTO generos (id, name) VALUES (50, 'art rock');
INSERT INTO generos (id, name) VALUES (51, 'mambo chileno');
INSERT INTO generos (id, name) VALUES (52, 'filmi');
INSERT INTO generos (id, name) VALUES (53, 'uk funky');
INSERT INTO generos (id, name) VALUES (54, 'urbano latino');
INSERT INTO generos (id, name) VALUES (55, 'french indie pop');
INSERT INTO generos (id, name) VALUES (56, 'country');
INSERT INTO generos (id, name) VALUES (57, 'pop soul');
INSERT INTO generos (id, name) VALUES (58, 'canadian rock');
INSERT INTO generos (id, name) VALUES (59, 'canadian old school hip hop');
INSERT INTO generos (id, name) VALUES (60, 'rap rock');
INSERT INTO generos (id, name) VALUES (61, 'industrial rock');
INSERT INTO generos (id, name) VALUES (62, 'east coast hip hop');
INSERT INTO generos (id, name) VALUES (63, 'glee club');
INSERT INTO generos (id, name) VALUES (64, 'pop');
INSERT INTO generos (id, name) VALUES (65, 'country dawn');
INSERT INTO generos (id, name) VALUES (66, 'pixie');
INSERT INTO generos (id, name) VALUES (67, 'korean old school hip hop');
INSERT INTO generos (id, name) VALUES (68, 'screamo');
INSERT INTO generos (id, name) VALUES (69, 'g funk');
INSERT INTO generos (id, name) VALUES (70, 'bass house');
INSERT INTO generos (id, name) VALUES (71, 'uk contemporary r&b');
INSERT INTO generos (id, name) VALUES (72, 'pop nacional');
INSERT INTO generos (id, name) VALUES (73, 'golden age hip hop');
INSERT INTO generos (id, name) VALUES (74, 'europop');
INSERT INTO generos (id, name) VALUES (75, 'k-pop');
INSERT INTO generos (id, name) VALUES (76, 'big beat');
INSERT INTO generos (id, name) VALUES (77, 'swedish indie pop');
INSERT INTO generos (id, name) VALUES (78, 'electropop');
INSERT INTO generos (id, name) VALUES (79, 'finnish edm');
INSERT INTO generos (id, name) VALUES (80, 'trap boricua');
INSERT INTO generos (id, name) VALUES (81, 'latin pop');
INSERT INTO generos (id, name) VALUES (82, 'puerto rican pop');
INSERT INTO generos (id, name) VALUES (83, 'rock independant francais');
INSERT INTO generos (id, name) VALUES (84, 'brighton indie');
INSERT INTO generos (id, name) VALUES (85, 'electro');
INSERT INTO generos (id, name) VALUES (86, 'australian electropop');
INSERT INTO generos (id, name) VALUES (87, 'crunk');
INSERT INTO generos (id, name) VALUES (88, 'happy hardcore');
INSERT INTO generos (id, name) VALUES (89, 'old school hip hop');
INSERT INTO generos (id, name) VALUES (90, 'new french touch');
INSERT INTO generos (id, name) VALUES (91, 'texas latin rap');
INSERT INTO generos (id, name) VALUES (92, 'rock');
INSERT INTO generos (id, name) VALUES (93, 'dutch house');
INSERT INTO generos (id, name) VALUES (94, 'modern alternative rock');
INSERT INTO generos (id, name) VALUES (95, 'pluggnb');
INSERT INTO generos (id, name) VALUES (96, 'pov: indie');
INSERT INTO generos (id, name) VALUES (97, 'house');
INSERT INTO generos (id, name) VALUES (98, 'g-house');
INSERT INTO generos (id, name) VALUES (99, 'dirty south rap');
INSERT INTO generos (id, name) VALUES (100, 'soca');
INSERT INTO generos (id, name) VALUES (101, 'garage rock revival');
INSERT INTO generos (id, name) VALUES (102, 'classic rock');
INSERT INTO generos (id, name) VALUES (103, 'north carolina hip hop');
INSERT INTO generos (id, name) VALUES (104, 'pop r&b');
INSERT INTO generos (id, name) VALUES (105, 'gauze pop');
INSERT INTO generos (id, name) VALUES (106, 'british singer-songwriter');
INSERT INTO generos (id, name) VALUES (107, 'r&b en espanol');
INSERT INTO generos (id, name) VALUES (108, 'conscious hip hop');
INSERT INTO generos (id, name) VALUES (109, 'dance-punk');
INSERT INTO generos (id, name) VALUES (110, 'big room');
INSERT INTO generos (id, name) VALUES (111, 'singer-songwriter pop');
INSERT INTO generos (id, name) VALUES (112, 'german dance');
INSERT INTO generos (id, name) VALUES (113, 'viral rap');
INSERT INTO generos (id, name) VALUES (114, 'mexican classic rock');
INSERT INTO generos (id, name) VALUES (115, 'escape room');
INSERT INTO generos (id, name) VALUES (116, 'nz pop');
INSERT INTO generos (id, name) VALUES (117, 'new orleans rap');
INSERT INTO generos (id, name) VALUES (118, 'quiet storm');
INSERT INTO generos (id, name) VALUES (119, 'alternative pop rock');
INSERT INTO generos (id, name) VALUES (120, 'new romantic');
INSERT INTO generos (id, name) VALUES (121, 'contemporary country');
INSERT INTO generos (id, name) VALUES (122, 'swedish electropop');
INSERT INTO generos (id, name) VALUES (123, 'chicano rap');
INSERT INTO generos (id, name) VALUES (124, 'filter house');
INSERT INTO generos (id, name) VALUES (125, 'album rock');
INSERT INTO generos (id, name) VALUES (126, 'political hip hop');
INSERT INTO generos (id, name) VALUES (127, 'icelandic rock');
INSERT INTO generos (id, name) VALUES (128, 'indie pop rap');
INSERT INTO generos (id, name) VALUES (129, 'italo dance');
INSERT INTO generos (id, name) VALUES (130, 'kentucky hip hop');
INSERT INTO generos (id, name) VALUES (131, 'mellow gold');
INSERT INTO generos (id, name) VALUES (132, 'electro trash');
INSERT INTO generos (id, name) VALUES (133, 'canadian punk');
INSERT INTO generos (id, name) VALUES (134, 'oktoberfest');
INSERT INTO generos (id, name) VALUES (135, 'gospel');
INSERT INTO generos (id, name) VALUES (136, 'industrial');
INSERT INTO generos (id, name) VALUES (137, 'latin arena pop');
INSERT INTO generos (id, name) VALUES (138, 'birmingham hip hop');
INSERT INTO generos (id, name) VALUES (139, 'shimmer pop');
INSERT INTO generos (id, name) VALUES (140, 'punk');
INSERT INTO generos (id, name) VALUES (141, 'bedroom pop');
INSERT INTO generos (id, name) VALUES (142, 'pop edm');
INSERT INTO generos (id, name) VALUES (143, 'disco house');
INSERT INTO generos (id, name) VALUES (144, 'tennessee hip hop');
INSERT INTO generos (id, name) VALUES (145, 'australian indie');
INSERT INTO generos (id, name) VALUES (146, 'downtempo');
INSERT INTO generos (id, name) VALUES (147, 'bubblegum dance');
INSERT INTO generos (id, name) VALUES (148, 'soul');
INSERT INTO generos (id, name) VALUES (149, 'neo-synthpop');
INSERT INTO generos (id, name) VALUES (150, 'leicester indie');
INSERT INTO generos (id, name) VALUES (151, 'brostep');
INSERT INTO generos (id, name) VALUES (152, 'german pop');
INSERT INTO generos (id, name) VALUES (153, 'australian talent show');
INSERT INTO generos (id, name) VALUES (154, 'gangster rap');
INSERT INTO generos (id, name) VALUES (155, 'reggae fusion');
INSERT INTO generos (id, name) VALUES (156, 'broadway');
INSERT INTO generos (id, name) VALUES (157, 'slowed and reverb');
INSERT INTO generos (id, name) VALUES (158, 'finnish alternative rock');
INSERT INTO generos (id, name) VALUES (159, 'glam metal');
INSERT INTO generos (id, name) VALUES (160, 'seattle indie');
INSERT INTO generos (id, name) VALUES (161, 'celtic rock');
INSERT INTO generos (id, name) VALUES (162, 'hollywood');
INSERT INTO generos (id, name) VALUES (163, 'sertanejo universitario');
INSERT INTO generos (id, name) VALUES (164, 'art pop');
INSERT INTO generos (id, name) VALUES (165, 'nyc rap');
INSERT INTO generos (id, name) VALUES (166, 'stomp pop');
INSERT INTO generos (id, name) VALUES (167, 'movie tunes');
INSERT INTO generos (id, name) VALUES (168, 'deep euro house');
INSERT INTO generos (id, name) VALUES (169, 'diva house');
INSERT INTO generos (id, name) VALUES (170, 'detroit rock');
INSERT INTO generos (id, name) VALUES (171, 'tropical house');
INSERT INTO generos (id, name) VALUES (172, 'florida drill');
INSERT INTO generos (id, name) VALUES (173, 'la indie');
INSERT INTO generos (id, name) VALUES (174, 'electro house');
INSERT INTO generos (id, name) VALUES (175, 'swedish synthpop');
INSERT INTO generos (id, name) VALUES (176, 'lilith');
INSERT INTO generos (id, name) VALUES (177, 'belgian dance');
INSERT INTO generos (id, name) VALUES (178, 'modern power pop');
INSERT INTO generos (id, name) VALUES (179, 'lounge');
INSERT INTO generos (id, name) VALUES (180, 'ohio hip hop');
INSERT INTO generos (id, name) VALUES (181, 'urban contemporary');
INSERT INTO generos (id, name) VALUES (182, 'london rap');
INSERT INTO generos (id, name) VALUES (183, 'socal pop punk');
INSERT INTO generos (id, name) VALUES (184, 'girl group');
INSERT INTO generos (id, name) VALUES (185, 'lgbtq+ hip hop');
INSERT INTO generos (id, name) VALUES (186, 'battle rap');
INSERT INTO generos (id, name) VALUES (187, 'supergroup');
INSERT INTO generos (id, name) VALUES (188, 'rock-and-roll');
INSERT INTO generos (id, name) VALUES (189, 'indie rock');
INSERT INTO generos (id, name) VALUES (190, 'dancefloor dnb');
INSERT INTO generos (id, name) VALUES (191, 'alternative r&b');
INSERT INTO generos (id, name) VALUES (192, 'country rap');
INSERT INTO generos (id, name) VALUES (193, 'new jersey rap');
INSERT INTO generos (id, name) VALUES (194, 'british alternative rock');
INSERT INTO generos (id, name) VALUES (195, 'nu metal');
INSERT INTO generos (id, name) VALUES (196, 'baton rouge rap');
INSERT INTO generos (id, name) VALUES (197, 'edm');
INSERT INTO generos (id, name) VALUES (198, 'nyc pop');
INSERT INTO generos (id, name) VALUES (199, 'neo-psychedelic');
INSERT INTO generos (id, name) VALUES (200, 'canadian latin');
INSERT INTO generos (id, name) VALUES (201, 'rockabilly');
INSERT INTO generos (id, name) VALUES (202, 'reggaeton colombiano');
INSERT INTO generos (id, name) VALUES (203, 'sertanejo');
INSERT INTO generos (id, name) VALUES (204, 'dutch trance');
INSERT INTO generos (id, name) VALUES (205, 'nigerian pop');
INSERT INTO generos (id, name) VALUES (206, 'wrestling');
INSERT INTO generos (id, name) VALUES (207, 'gen z singer-songwriter');
INSERT INTO generos (id, name) VALUES (208, 'romanian pop');
INSERT INTO generos (id, name) VALUES (209, 'west coast rap');
INSERT INTO generos (id, name) VALUES (210, 'hardcore punk');
INSERT INTO generos (id, name) VALUES (211, 'hardcore techno');
INSERT INTO generos (id, name) VALUES (212, 'trap argentino');
INSERT INTO generos (id, name) VALUES (213, 'post-grunge');
INSERT INTO generos (id, name) VALUES (214, 'bhangra');
INSERT INTO generos (id, name) VALUES (215, 'blues rock');
INSERT INTO generos (id, name) VALUES (216, 'australian pop');
INSERT INTO generos (id, name) VALUES (217, 'dutch pop');
INSERT INTO generos (id, name) VALUES (218, 'pop rock');
INSERT INTO generos (id, name) VALUES (219, 'instrumental grime');
INSERT INTO generos (id, name) VALUES (220, 'black americana');
INSERT INTO generos (id, name) VALUES (221, 'k-pop boy group');
INSERT INTO generos (id, name) VALUES (222, 'asian american hip hop');
INSERT INTO generos (id, name) VALUES (223, 'washington indie');
INSERT INTO generos (id, name) VALUES (224, 'baroque pop');
INSERT INTO generos (id, name) VALUES (225, 'indie rock italiano');
INSERT INTO generos (id, name) VALUES (226, 'houston rap');
INSERT INTO generos (id, name) VALUES (227, 'oakland hip hop');
INSERT INTO generos (id, name) VALUES (228, 'south african rock');
INSERT INTO generos (id, name) VALUES (229, 'eurodance');
INSERT INTO generos (id, name) VALUES (230, 'scottish singer-songwriter');
INSERT INTO generos (id, name) VALUES (231, 'bronx hip hop');
INSERT INTO generos (id, name) VALUES (232, 'dream pop');
INSERT INTO generos (id, name) VALUES (233, 'grunge');
INSERT INTO generos (id, name) VALUES (234, 'minneapolis sound');
INSERT INTO generos (id, name) VALUES (235, 'pittsburgh rap');
INSERT INTO generos (id, name) VALUES (236, 'vocal jazz');
INSERT INTO generos (id, name) VALUES (237, 'swedish idol pop');
INSERT INTO generos (id, name) VALUES (238, 'funk rj');
INSERT INTO generos (id, name) VALUES (239, 'pop venezolano');
INSERT INTO generos (id, name) VALUES (240, 'urbano chileno');
INSERT INTO generos (id, name) VALUES (241, 'hip pop');
INSERT INTO generos (id, name) VALUES (242, 'christian alternative rock');
INSERT INTO generos (id, name) VALUES (243, 'deep house');
INSERT INTO generos (id, name) VALUES (244, 'folk-pop');
INSERT INTO generos (id, name) VALUES (245, 'vincy soca');
INSERT INTO generos (id, name) VALUES (246, 'atl hip hop');
INSERT INTO generos (id, name) VALUES (247, 'trap latino');
INSERT INTO generos (id, name) VALUES (248, 'uk americana');
INSERT INTO generos (id, name) VALUES (249, 'hamburg electronic');
INSERT INTO generos (id, name) VALUES (250, 'cloud rap');
INSERT INTO generos (id, name) VALUES (251, 'melodic rap');
INSERT INTO generos (id, name) VALUES (252, 'canadian metal');
INSERT INTO generos (id, name) VALUES (253, 'canadian electropop');
INSERT INTO generos (id, name) VALUES (254, 'old school atlanta hip hop');
INSERT INTO generos (id, name) VALUES (255, 'australian hip hop');
INSERT INTO generos (id, name) VALUES (256, 'rage rap');
INSERT INTO generos (id, name) VALUES (257, 'neon pop punk');
INSERT INTO generos (id, name) VALUES (258, 'modern salsa');
INSERT INTO generos (id, name) VALUES (259, 'chill pop');
INSERT INTO generos (id, name) VALUES (260, 'breakbeat');
INSERT INTO generos (id, name) VALUES (261, 'rock en espanol');
INSERT INTO generos (id, name) VALUES (262, 'trip hop');
INSERT INTO generos (id, name) VALUES (263, 'british invasion');
INSERT INTO generos (id, name) VALUES (264, 'israeli pop');
INSERT INTO generos (id, name) VALUES (265, 'pop dance');
INSERT INTO generos (id, name) VALUES (266, 'funk metal');
INSERT INTO generos (id, name) VALUES (267, 'dark clubbing');
INSERT INTO generos (id, name) VALUES (268, 'norwegian hip hop');
INSERT INTO generos (id, name) VALUES (269, 'canadian trap');
INSERT INTO generos (id, name) VALUES (270, 'contemporary vocal jazz');
INSERT INTO generos (id, name) VALUES (271, 'afrofuturism');
INSERT INTO generos (id, name) VALUES (272, 'norwegian pop');
INSERT INTO generos (id, name) VALUES (273, 'k-pop girl group');
INSERT INTO generos (id, name) VALUES (274, 'modern blues rock');
INSERT INTO generos (id, name) VALUES (275, 'rap metal');
INSERT INTO generos (id, name) VALUES (276, 'minnesota hip hop');
INSERT INTO generos (id, name) VALUES (277, 'canadian contemporary r&b');
INSERT INTO generos (id, name) VALUES (278, 'indie folk');
INSERT INTO generos (id, name) VALUES (279, 'australian house');
INSERT INTO generos (id, name) VALUES (280, 'grave wave');
INSERT INTO generos (id, name) VALUES (281, 'country road');
INSERT INTO generos (id, name) VALUES (282, 'oxford indie');
INSERT INTO generos (id, name) VALUES (283, 'sad rap');
INSERT INTO generos (id, name) VALUES (284, 'alternative dance');
INSERT INTO generos (id, name) VALUES (285, 'indietronica');
INSERT INTO generos (id, name) VALUES (286, 'seattle hip hop');
INSERT INTO generos (id, name) VALUES (287, 'chicago bop');
INSERT INTO generos (id, name) VALUES (288, 'northern irish indie');
INSERT INTO generos (id, name) VALUES (289, 'virginia hip hop');
INSERT INTO generos (id, name) VALUES (290, 'italian pop');
INSERT INTO generos (id, name) VALUES (291, 'swedish tropical house');
INSERT INTO generos (id, name) VALUES (292, 'afrobeats');
INSERT INTO generos (id, name) VALUES (293, 'indie anthem-folk');
INSERT INTO generos (id, name) VALUES (294, 'sad lo-fi');
INSERT INTO generos (id, name) VALUES (295, 'dancehall');
INSERT INTO generos (id, name) VALUES (296, 'queens hip hop');
INSERT INTO generos (id, name) VALUES (297, 'alternative metal');
INSERT INTO generos (id, name) VALUES (298, 'r&b');
INSERT INTO generos (id, name) VALUES (299, 'ukg revival');
INSERT INTO generos (id, name) VALUES (300, 'rap kreyol');
INSERT INTO generos (id, name) VALUES (301, 'brooklyn drill');
INSERT INTO generos (id, name) VALUES (302, 'new jack swing');
INSERT INTO generos (id, name) VALUES (303, 'hands up');
INSERT INTO generos (id, name) VALUES (304, 'permanent wave');
INSERT INTO generos (id, name) VALUES (305, 'middle earth');
INSERT INTO generos (id, name) VALUES (306, 'uk dance');
INSERT INTO generos (id, name) VALUES (307, 'progressive house');
INSERT INTO generos (id, name) VALUES (308, 'metropopolis');
INSERT INTO generos (id, name) VALUES (309, 'alternative hip hop');
INSERT INTO generos (id, name) VALUES (310, 'mexican pop');
INSERT INTO generos (id, name) VALUES (311, 'glam rock');
INSERT INTO generos (id, name) VALUES (312, 'speed garage');
INSERT INTO generos (id, name) VALUES (313, 'punk blues');
INSERT INTO generos (id, name) VALUES (314, 'latin hip hop');
INSERT INTO generos (id, name) VALUES (315, 'progressive electro house');
INSERT INTO generos (id, name) VALUES (316, 'beatlesque');
INSERT INTO generos (id, name) VALUES (317, 'argentine hip hop');
INSERT INTO generos (id, name) VALUES (318, 'electronic trap');
INSERT INTO generos (id, name) VALUES (319, 'k-rap');
INSERT INTO generos (id, name) VALUES (320, 'melodic drill');
INSERT INTO generos (id, name) VALUES (321, 'reggaeton flow');
INSERT INTO generos (id, name) VALUES (322, 'rave');
INSERT INTO generos (id, name) VALUES (323, 'indie pop');
INSERT INTO generos (id, name) VALUES (324, 'bouncy house');
INSERT INTO generos (id, name) VALUES (325, 'canadian indie');
INSERT INTO generos (id, name) VALUES (326, 'bounce');
INSERT INTO generos (id, name) VALUES (327, 'virgin islands reggae');
INSERT INTO generos (id, name) VALUES (328, 'boy band');
INSERT INTO generos (id, name) VALUES (329, 'mississippi hip hop');
INSERT INTO generos (id, name) VALUES (330, 'australian dance');
INSERT INTO generos (id, name) VALUES (331, 'harlem hip hop');
INSERT INTO generos (id, name) VALUES (332, 'indie poptimism');
INSERT INTO generos (id, name) VALUES (333, 'slap house');
INSERT INTO generos (id, name) VALUES (334, 'christian music');
INSERT INTO generos (id, name) VALUES (335, 'hyphy');
INSERT INTO generos (id, name) VALUES (336, 'french synthpop');
INSERT INTO generos (id, name) VALUES (337, 'trap');
INSERT INTO generos (id, name) VALUES (338, 'st louis rap');
INSERT INTO generos (id, name) VALUES (339, 'detroit hip hop');
INSERT INTO generos (id, name) VALUES (340, 'dance pop');
INSERT INTO generos (id, name) VALUES (341, 'etherpop');
INSERT INTO generos (id, name) VALUES (342, 'memphis hip hop');
INSERT INTO generos (id, name) VALUES (343, 'melbourne bounce');
INSERT INTO generos (id, name) VALUES (344, 'bedroom soul');
INSERT INTO generos (id, name) VALUES (345, 'acid house');
INSERT INTO generos (id, name) VALUES (346, 'idol');
INSERT INTO generos (id, name) VALUES (347, 'dfw rap');
INSERT INTO generos (id, name) VALUES (348, 'australian alternative rock');
INSERT INTO generos (id, name) VALUES (349, 'trap queen');
INSERT INTO generos (id, name) VALUES (350, 'moldovan pop');
INSERT INTO generos (id, name) VALUES (351, 'eau claire indie');
INSERT INTO generos (id, name) VALUES (352, 'talent show');
INSERT INTO generos (id, name) VALUES (353, 'southern hip hop');
INSERT INTO generos (id, name) VALUES (354, 'belgian pop');
INSERT INTO generos (id, name) VALUES (355, 'alternative rock');
INSERT INTO generos (id, name) VALUES (356, 'chamber pop');
INSERT INTO generos (id, name) VALUES (357, 'jazz pop');
INSERT INTO generos (id, name) VALUES (358, 'industrial metal');
INSERT INTO generos (id, name) VALUES (359, 'comic');
INSERT INTO generos (id, name) VALUES (360, 'piano rock');
INSERT INTO generos (id, name) VALUES (361, 'hip hop');
INSERT INTO generos (id, name) VALUES (362, 'soft rock');
INSERT INTO generos (id, name) VALUES (363, 'rhode island rap');
INSERT INTO generos (id, name) VALUES (364, 'uk pop');
INSERT INTO generos (id, name) VALUES (365, 'viral trap');
INSERT INTO generos (id, name) VALUES (366, 'florida rap');
INSERT INTO generos (id, name) VALUES (367, 'drum and bass');
INSERT INTO generos (id, name) VALUES (368, 'belgian edm');
INSERT INTO generos (id, name) VALUES (369, 'hard rock');
INSERT INTO generos (id, name) VALUES (370, 'scottish rock');
INSERT INTO generos (id, name) VALUES (371, 'deep underground hip hop');
INSERT INTO generos (id, name) VALUES (372, 'skate punk');
INSERT INTO generos (id, name) VALUES (373, 'contemporary r&b');
INSERT INTO generos (id, name) VALUES (374, 'danish pop');
INSERT INTO generos (id, name) VALUES (375, 'dance rock');
INSERT INTO generos (id, name) VALUES (376, 'celtic');
INSERT INTO generos (id, name) VALUES (377, 'comedy rap');
INSERT INTO generos (id, name) VALUES (378, 'viral pop');
INSERT INTO generos (id, name) VALUES (379, 'electronica');
INSERT INTO generos (id, name) VALUES (380, 'miami hip hop');
INSERT INTO generos (id, name) VALUES (381, 'hawaiian hip hop');
INSERT INTO generos (id, name) VALUES (382, 'french shoegaze');
INSERT INTO generos (id, name) VALUES (383, 'welsh rock');
INSERT INTO generos (id, name) VALUES (384, 'atlanta bass');
INSERT INTO generos (id, name) VALUES (385, 'gospel r&b');
INSERT INTO generos (id, name) VALUES (386, 'uk hip hop');
INSERT INTO generos (id, name) VALUES (387, 'modern folk rock');
INSERT INTO generos (id, name) VALUES (388, 'irish singer-songwriter');
INSERT INTO generos (id, name) VALUES (389, 'cali rap');
INSERT INTO generos (id, name) VALUES (390, 'grime');
INSERT INTO generos (id, name) VALUES (391, 'alt z');
INSERT INTO generos (id, name) VALUES (392, 'canadian hip hop');
INSERT INTO generos (id, name) VALUES (393, 'country pop');
INSERT INTO generos (id, name) VALUES (394, 'plugg');
INSERT INTO generos (id, name) VALUES (395, 'shiver pop');
INSERT INTO generos (id, name) VALUES (396, 'britpop');
INSERT INTO generos (id, name) VALUES (397, 'moombahton');
INSERT INTO generos (id, name) VALUES (398, 'funk rock');
INSERT INTO generos (id, name) VALUES (399, 'australian rock');
INSERT INTO generos (id, name) VALUES (400, 'show tunes');
INSERT INTO generos (id, name) VALUES (401, 'irish pop');
INSERT INTO generos (id, name) VALUES (402, 'reggaeton');
INSERT INTO generos (id, name) VALUES (403, 'schlager');
INSERT INTO generos (id, name) VALUES (404, 'pop rap');
INSERT INTO generos (id, name) VALUES (405, 'classic house');
INSERT INTO generos (id, name) VALUES (406, 'candy pop');
INSERT INTO generos (id, name) VALUES (407, 'classic schlager');
INSERT INTO generos (id, name) VALUES (408, 'melbourne bounce international');
INSERT INTO generos (id, name) VALUES (409, 'bahamian pop');
INSERT INTO generos (id, name) VALUES (410, 'pagode baiano');
INSERT INTO generos (id, name) VALUES (411, 'sophisti-pop');
INSERT INTO generos (id, name) VALUES (412, 'old school bassline');
INSERT INTO generos (id, name) VALUES (413, 'underground hip hop');
INSERT INTO generos (id, name) VALUES (414, 'latin viral pop');
INSERT INTO generos (id, name) VALUES (415, 'barbadian pop');
INSERT INTO generos (id, name) VALUES (416, 'english indie rock');
INSERT INTO generos (id, name) VALUES (417, 'german techno');
INSERT INTO generos (id, name) VALUES (418, 'norwegian indie');
INSERT INTO generos (id, name) VALUES (419, 'swedish pop');
INSERT INTO generos (id, name) VALUES (420, 'south carolina hip hop');
INSERT INTO generos (id, name) VALUES (421, 'emo');
INSERT INTO generos (id, name) VALUES (422, 'colombian pop');
INSERT INTO generos (id, name) VALUES (423, 'acoustic pop');
INSERT INTO generos (id, name) VALUES (424, 'sheffield indie');
INSERT INTO generos (id, name) VALUES (425, 'madchester');
INSERT INTO generos (id, name) VALUES (426, 'post-teen pop');
INSERT INTO generos (id, name) VALUES (427, 'uk garage');
INSERT INTO generos (id, name) VALUES (428, 'desi hip hop');
INSERT INTO generos (id, name) VALUES (429, 'new wave');
INSERT INTO generos (id, name) VALUES (430, 'french rock');
INSERT INTO generos (id, name) VALUES (431, 'lds youth');
INSERT INTO generos (id, name) VALUES (432, 'uk alternative pop');
INSERT INTO generos (id, name) VALUES (433, 'classic oklahoma country');
INSERT INTO generos (id, name) VALUES (434, 'vocal house');
INSERT INTO generos (id, name) VALUES (435, 'classic bhangra');
INSERT INTO generos (id, name) VALUES (436, 'san diego rap');
INSERT INTO generos (id, name) VALUES (437, 'chicago rap');
